name: medico
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.16.0
  firebase_core: 2.32.0
  google_sign_in: ^6.0.0
  flutter_facebook_auth: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/spalsh_screen.png
    - assets/360_F_707893394_5DEhlBjWOmse1nyu0rC9T7ZRvsAFDkYC.jpg
    - assets/giphy.gif
    - assets/istockphoto-479378798-612x612.jpg
    - assets/onboarding_1.png
